In [2]:
import pandas as pd
import pandas as pd

In [3]:
data = pd.read_csv("Pune_house_data.csv")

In [4]:
data.drop(columns = ['area_type','availability','society'],inplace = True)

In [5]:
data.dropna(inplace =True)

In [6]:
data

            size total_sqft  bath  balcony   price         site_location
0          2 BHK       1056   2.0      1.0   39.07           Alandi Road
1      4 Bedroom       2600   5.0      3.0  120.00       Ambegaon Budruk
2          3 BHK       1440   2.0      3.0   62.00            Anandnagar
3          3 BHK       1521   3.0      1.0   95.00                 Aundh
4          2 BHK       1200   2.0      1.0   51.00            Aundh Road
...          ...        ...   ...      ...     ...                   ...
13314      3 BHK       1715   3.0      3.0  112.00       Parvati Darshan
13315  5 Bedroom       3453   4.0      0.0  231.00                Pashan
13317      2 BHK       1141   2.0      1.0   60.00              Pirangut
13318      4 BHK       4689   4.0      1.0  488.00          Prabhat Road
13319      1 BHK        550   1.0      1.0   17.00  Pune Railway Station

[12710 rows x 6 columns]

In [7]:
data.site_location.value_counts()

site_location
Ambegaon Budruk     136
Dhole Patil Road    136
Kalyani Nagar       136
Dhayari Phata       136
Wagholi             136
                   ...
Aundh               128
Wanowrie            128
Khadaki             128
Manik Bagh          127
other                 1
Name: count, Length: 97, dtype: int64

In [8]:
data["site_location"] = data["site_location"].apply(lambda x : x.strip())

In [9]:
data.site_location.value_counts()

site_location
Ambegaon Budruk     136
Dhole Patil Road    136
Kalyani Nagar       136
Dhayari Phata       136
Wagholi             136
                   ...
Aundh               128
Wanowrie            128
Khadaki             128
Manik Bagh          127
other                 1
Name: count, Length: 97, dtype: int64

In [10]:
location_stats = data.groupby("site_location")["site_location"].agg("count").sort_values(ascending =False)

In [11]:
location_stats

site_location
Ambegaon Budruk     136
Dhole Patil Road    136
Dhayari Phata       136
Sasson Road         136
Wagholi             136
                   ...
Khadaki             128
Wanowrie            128
Vadgaon Budruk      128
Manik Bagh          127
other                 1
Name: site_location, Length: 97, dtype: int64

In [12]:
location_less_than_10_entries = location_stats[location_stats <= 10]

In [13]:
location_less_than_10_entries

site_location
other    1
Name: site_location, dtype: int64

In [14]:
data["site_location"]= data["site_location"].apply(lambda x : "other" if x in location_less_than_10_entries else x)

In [15]:
data.site_location.value_counts()

site_location
Ambegaon Budruk     136
Dhole Patil Road    136
Kalyani Nagar       136
Dhayari Phata       136
Wagholi             136
                   ...
Aundh               128
Wanowrie            128
Khadaki             128
Manik Bagh          127
other                 1
Name: count, Length: 97, dtype: int64

In [16]:
data

            size total_sqft  bath  balcony   price         site_location
0          2 BHK       1056   2.0      1.0   39.07           Alandi Road
1      4 Bedroom       2600   5.0      3.0  120.00       Ambegaon Budruk
2          3 BHK       1440   2.0      3.0   62.00            Anandnagar
3          3 BHK       1521   3.0      1.0   95.00                 Aundh
4          2 BHK       1200   2.0      1.0   51.00            Aundh Road
...          ...        ...   ...      ...     ...                   ...
13314      3 BHK       1715   3.0      3.0  112.00       Parvati Darshan
13315  5 Bedroom       3453   4.0      0.0  231.00                Pashan
13317      2 BHK       1141   2.0      1.0   60.00              Pirangut
13318      4 BHK       4689   4.0      1.0  488.00          Prabhat Road
13319      1 BHK        550   1.0      1.0   17.00  Pune Railway Station

[12710 rows x 6 columns]

In [17]:
data['size'].unique()

array(['2 BHK', '4 Bedroom', '3 BHK', '3 Bedroom', '1 BHK', '1 RK',
       '4 BHK', '1 Bedroom', '2 Bedroom', '6 Bedroom', '8 Bedroom',
       '7 Bedroom', '5 BHK', '7 BHK', '6 BHK', '5 Bedroom', '11 BHK',
       '9 BHK', '9 Bedroom', '27 BHK', '11 Bedroom', '43 Bedroom',
       '14 BHK', '8 BHK', '12 Bedroom', '10 Bedroom', '13 BHK'],
      dtype=object)

In [18]:
data['bedrooms']=data['size'].apply(lambda x : int (x.split(' ')[0]))

In [19]:
data.total_sqft.unique()

array(['1056', '2600', '1440', ..., '1133 - 1384', '774', '4689'],
      shape=(1976,), dtype=object)

In [20]:
def clean(sqft):
    tokens = sqft.split('-')
    if len(tokens) == 2:
        return (float(tokens[0]) + float(tokens[1])) / 2
    else:
        try:
            return float(sqft)
        except:
            return None

print(clean('200'))        # 200.0
print(clean('100-200'))    # 150.0

200.0
150.0

In [21]:
data['total_sqft'] = data['total_sqft'].apply(clean)

In [22]:
data['total_sqft'].unique()

array([1056. , 2600. , 1440. , ..., 1258.5,  774. , 4689. ], shape=(1887,))

In [23]:
data.describe()

         total_sqft          bath       balcony         price      bedrooms
count  12668.000000  12710.000000  12710.000000  12710.000000  12710.000000
mean    1511.888846      2.617388      1.584500    106.064790      2.737215
std     1162.085641      1.225992      0.817175    131.764701      1.205082
min        5.000000      1.000000      0.000000      8.000000      1.000000
25%     1100.000000      2.000000      1.000000     49.062500      2.000000
50%     1260.000000      2.000000      2.000000     70.000000      3.000000
75%     1640.000000      3.000000      2.000000    115.000000      3.000000
max    52272.000000     40.000000      3.000000   2912.000000     43.000000

In [24]:
data.dropna(inplace=True)

In [25]:
data

,size,total_sqft,bath,balcony,price,site_location,bedrooms
0,2 BHK,1056.0,2.0,1.0,39.07,Alandi Road,2
1,4 Bedroom,2600.0,5.0,3.0,120.00,Ambegaon Budruk,4
2,3 BHK,1440.0,2.0,3.0,62.00,Anandnagar,3
3,3 BHK,1521.0,3.0,1.0,95.00,Aundh,3
4,2 BHK,1200.0,2.0,1.0,51.00,Aundh Road,2
...,...,...,...,...,...,...,...
13314,3 BHK,1715.0,3.0,3.0,112.00,Parvati Darshan,3
13315,5 Bedroom,3453.0,4.0,0.0,231.00,Pashan,5
13317,2 BHK,1141.0,2.0,1.0,60.00,Pirangut,2
13318,4 BHK,4689.0,4.0,1.0,488.00,Prabhat Road,4
13319,1 BHK,550.0,1.0,1.0,17.00,Pune Railway Station,1

In [26]:
data.describe()

         total_sqft          bath       balcony         price      bedrooms
count  12668.000000  12668.000000  12668.000000  12668.000000  12668.000000
mean    1511.888846      2.616356      1.585807    105.956674      2.736501
std     1162.085641      1.223874      0.816645    131.811748      1.202627
min        5.000000      1.000000      0.000000      8.000000      1.000000
25%     1100.000000      2.000000      1.000000     49.050000      2.000000
50%     1260.000000      2.000000      2.000000     70.000000      3.000000
75%     1640.000000      3.000000      2.000000    115.000000      3.000000
max    52272.000000     40.000000      3.000000   2912.000000     43.000000

In [27]:
data['sqft_per_bed'] = data['total_sqft']/data['bedrooms']

In [28]:
data.sqft_per_bed.describe()

count    12668.000000
mean       570.066080
std        380.297882
min          0.714286
25%        473.333333
50%        550.000000
75%        622.500000
max      26136.000000
Name: sqft_per_bed, dtype: float64

In [29]:
data2 = data[data['sqft_per_bed'] >= 300]

In [30]:
data2

,size,total_sqft,bath,balcony,price,site_location,bedrooms,sqft_per_bed
0,2 BHK,1056.0,2.0,1.0,39.07,Alandi Road,2,528.000000
1,4 Bedroom,2600.0,5.0,3.0,120.00,Ambegaon Budruk,4,650.000000
2,3 BHK,1440.0,2.0,3.0,62.00,Anandnagar,3,480.000000
3,3 BHK,1521.0,3.0,1.0,95.00,Aundh,3,507.000000
4,2 BHK,1200.0,2.0,1.0,51.00,Aundh Road,2,600.000000
...,...,...,...,...,...,...,...,...
13314,3 BHK,1715.0,3.0,3.0,112.00,Parvati Darshan,3,571.666667
13315,5 Bedroom,3453.0,4.0,0.0,231.00,Pashan,5,690.600000
13317,2 BHK,1141.0,2.0,1.0,60.00,Pirangut,2,570.500000
13318,4 BHK,4689.0,4.0,1.0,488.00,Prabhat Road,4,1172.250000
13319,1 BHK,550.0,1.0,1.0,17.00,Pune Railway Station,1,550.000000

In [31]:
data2['price_per_sqft'] = data2['price']*100000/data2['total_sqft']

C:\Users\lalit\AppData\Local\Temp\ipykernel_34756\1544858762.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data2['price_per_sqft'] = data2['price']*100000/data2['total_sqft']

In [32]:
data2

,size,total_sqft,bath,balcony,price,site_location,bedrooms,sqft_per_bed,price_per_sqft
0,2 BHK,1056.0,2.0,1.0,39.07,Alandi Road,2,528.000000,3699.810606
1,4 Bedroom,2600.0,5.0,3.0,120.00,Ambegaon Budruk,4,650.000000,4615.384615
2,3 BHK,1440.0,2.0,3.0,62.00,Anandnagar,3,480.000000,4305.555556
3,3 BHK,1521.0,3.0,1.0,95.00,Aundh,3,507.000000,6245.890861
4,2 BHK,1200.0,2.0,1.0,51.00,Aundh Road,2,600.000000,4250.000000
...,...,...,...,...,...,...,...,...,...
13314,3 BHK,1715.0,3.0,3.0,112.00,Parvati Darshan,3,571.666667,6530.612245
13315,5 Bedroom,3453.0,4.0,0.0,231.00,Pashan,5,690.600000,6689.834926
13317,2 BHK,1141.0,2.0,1.0,60.00,Pirangut,2,570.500000,5258.545136
13318,4 BHK,4689.0,4.0,1.0,488.00,Prabhat Road,4,1172.250000,10407.336319
13319,1 BHK,550.0,1.0,1.0,17.00,Pune Railway Station,1,550.000000,3090.909091

In [33]:
data2.price_per_sqft.describe()

count     12013.000000
mean       6206.213093
std        3985.465773
min         267.829813
25%        4199.565960
50%        5253.456221
75%        6823.529412
max      176470.588235
Name: price_per_sqft, dtype: float64

In [34]:
data3 = data2[data2['price_per_sqft'] >= 2000]

In [35]:
data3['price_per_sqft'].describe()

count     11985.000000
mean       6217.670678
std        3982.974688
min        2000.000000
25%        4200.000000
50%        5263.157895
75%        6832.861190
max      176470.588235
Name: price_per_sqft, dtype: float64

In [36]:
data3

,size,total_sqft,bath,balcony,price,site_location,bedrooms,sqft_per_bed,price_per_sqft
0,2 BHK,1056.0,2.0,1.0,39.07,Alandi Road,2,528.000000,3699.810606
1,4 Bedroom,2600.0,5.0,3.0,120.00,Ambegaon Budruk,4,650.000000,4615.384615
2,3 BHK,1440.0,2.0,3.0,62.00,Anandnagar,3,480.000000,4305.555556
3,3 BHK,1521.0,3.0,1.0,95.00,Aundh,3,507.000000,6245.890861
4,2 BHK,1200.0,2.0,1.0,51.00,Aundh Road,2,600.000000,4250.000000
...,...,...,...,...,...,...,...,...,...
13314,3 BHK,1715.0,3.0,3.0,112.00,Parvati Darshan,3,571.666667,6530.612245
13315,5 Bedroom,3453.0,4.0,0.0,231.00,Pashan,5,690.600000,6689.834926
13317,2 BHK,1141.0,2.0,1.0,60.00,Pirangut,2,570.500000,5258.545136
13318,4 BHK,4689.0,4.0,1.0,488.00,Prabhat Road,4,1172.250000,10407.336319
13319,1 BHK,550.0,1.0,1.0,17.00,Pune Railway Station,1,550.000000,3090.909091

In [37]:
data3.drop(columns = ['size','sqft_per_bed','price_per_sqft'],axis =1,inplace= True)

C:\Users\lalit\AppData\Local\Temp\ipykernel_34756\2804110138.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data3.drop(columns = ['size','sqft_per_bed','price_per_sqft'],axis =1,inplace= True)

In [38]:
data3

       total_sqft  bath  balcony   price         site_location  bedrooms
0          1056.0   2.0      1.0   39.07           Alandi Road         2
1          2600.0   5.0      3.0  120.00       Ambegaon Budruk         4
2          1440.0   2.0      3.0   62.00            Anandnagar         3
3          1521.0   3.0      1.0   95.00                 Aundh         3
4          1200.0   2.0      1.0   51.00            Aundh Road         2
...           ...   ...      ...     ...                   ...       ...
13314      1715.0   3.0      3.0  112.00       Parvati Darshan         3
13315      3453.0   4.0      0.0  231.00                Pashan         5
13317      1141.0   2.0      1.0   60.00              Pirangut         2
13318      4689.0   4.0      1.0  488.00          Prabhat Road         4
13319       550.0   1.0      1.0   17.00  Pune Railway Station         1

[11985 rows x 6 columns]

In [39]:
from sklearn.preprocessing import OneHotEncoder,StandardScaler

In [40]:
from sklearn.model_selection import train_test_split

In [41]:
from sklearn.linear_model import LinearRegression

In [42]:
from sklearn.pipeline import make_pipeline

In [43]:
from sklearn.compose import make_column_transformer

In [44]:
col_trans = make_column_transformer((OneHotEncoder(sparse_output = False),['site_location']),remainder = 'passthrough')

In [45]:
lr = LinearRegression()

In [46]:
sr = StandardScaler()

In [47]:
model = make_pipeline(col_trans,sr,lr)

In [48]:
data_input = data3.drop(columns = ['price'])
data_output = data3['price']

In [49]:
x_train,x_test,y_train,y_test = train_test_split(data_input,data_output,test_size = 0.2)

In [50]:
model.fit(x_train,y_train)

C:\Users\lalit\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\compose\_column_transformer.py:1667: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('onehotencoder',
                                                  OneHotEncoder(sparse_output=False),
                                                  ['site_location'])])),
                ('standardscaler', StandardScaler()),
                ('linearregression', LinearRegression())])

In [51]:
model.score(x_test,y_test)

0.5370231457542469

In [55]:
input = pd.DataFrame([[1500.0,2.0,1.0,39.07,'Alandi Road',2]],columns=['total_sqft','bath','balcony','price','site_location','bedrooms'])

In [56]:
model.predict(input)

array([112.27364974])

In [57]:
import pickle as pk

In [58]:
pk.dump(model,open('House_prediction_model.pkl','wb'))

In [59]:
data3.to_csv('Cleaned_data.csv')